### ISSUE TITLE
假人会和提米的传送插件有冲突，由于假人没有xuid，在使用提米的传送超时后，会在控制台疯狂刷报错日志

### ISSUE THREAD

**Issue by Arnolwutong** [xiaoqch/LLFakePlayer#3]
假人会和提米的基础插件里的传送插功能有冲突
由于假人没有xuid，在使用提米的传送超时后，会在控制台疯狂刷报错日志

**Comment by Arnolwutong** [comment]
![QQ截图20220620012041](https://user-images.githubusercontent.com/95761056/174492925-cd4a1677-65de-4be8-b756-8ac2ab4d52ae.png)
也跟提米反馈了，说是解决不了。没有xuid就是无法写入数据库的

**Comment by xiaoqch** [comment]
是和bds的模拟玩家冲突，该插件不兼容模拟玩家存在的情况，与本插件无关，本插件外其他方式创建的模拟玩家也是一样的特征
